org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=128m -Dfile.encoding=UTF-8

org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=true
org.gradle.caching=true

android.useAndroidX=true

# This newDsl flag was added by the Flutter template
android.newDsl=false

# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false